Repository know-how-ai/know-how-BE, pull requests merged in 2023-08, with the labels that each got.

#8 Up to date by main
  .github/workflows/github-actions.yaml
  README.md
  app.js
  jest.config.js
  package.json
  server.js
  tests/app.test.js
Labels: Pull by main

#11 Up to date by main
  .eslintrc.json
  .github/workflows/github-actions.yaml
  .prettierrc.json
  README.md
  app.js
  jest.config.js
  server.js
  tests/app.test.js
Labels: Pull by main

#12 [ADD] 기본 라우팅 설정
  app.js
  package-lock.json
  package.json
  routes/index.js
  routes/kogpt.js
  routes/user.js
Labels: Add

#13 Pull by main
  app.js
  package-lock.json
  package.json
  routes/index.js
  routes/kogpt.js
  routes/user.js
Labels: Pull by main

#15 [CHORE] 의존성 패키지 재분류
  package-lock.json
  package.json
Labels: Add, Chore

#16 [ADD] Connect MySQL using Sequalize
  app.js
  model/index.js
  models/index.js
  models/pointLogs.js
  models/users.js
  package-lock.json
  package.json
  routes/kogpt.js
Labels: Add

#18 Pull by main
  app.js
  model/index.js
  models/index.js
  models/pointLogs.js
  models/users.js
  package-lock.json
  package.json
  routes/kogpt.js
Labels: Pull by main

#19 [FIX] Modified DB Schema
  models/pointLogs.js
  models/users.js
Labels: Fix

#20 [ADD] API 분기 처리 및 구체화
  routes/kogpt.js
  routes/user.js
Labels: Add

#21 [FIX] Modified Users Model
  models/users.js
Labels: Fix

#22 [ADD] 컨트롤러 구현 및 연결(`user`)
  controllers/point.js
  controllers/user.js
  package-lock.json
  package.json
  routes/user.js
Labels: Add

#23 [ADD] Applying CORS middleware
  app.js
Labels: Add

#24 [ADD] 포인트 로그 시스템(지급 파트), 유틸리티 모듈
  controllers/point.js
  controllers/user.js
  libs/date.js
  libs/hash.js
  routes/user.js
Labels: Fix, Add

#25 [FIX] 코드베이스 오류 및 오타 수정
  routes/user.js
Labels: bug, Fix

#26 [FIX] Modified Function Name
  controllers/index.js
  controllers/point.js
  routes/kogpt.js
Labels: bug, Fix

#27 [CHORE] Refactoring names
  app.js
  controllers/point.js
  controllers/user.js
  libs/date.js
  routes/user.js
Labels: Add, Chore

#28 [ADD] Set `passport.js` boilerplate, etc.
  app.js
  controllers/point.js
  controllers/user.js
  libs/date.js
  middlewares/errorHandler.js
  middlewares/private.js
  package-lock.json
  package.json
  passport/index.js
  passport/localStrategy.js
Labels: Add, Chore

#29 [FIX] 유저 라우터 - `passport.js` 적용
  routes/user.js
Labels: Fix

#30 [FIX] User Router
  routes/kogpt.js
  routes/user.js
Labels: Fix, Chore

#31 [ADD] user controller `deleteUserById`
  controllers/point.js
  controllers/user.js
  routes/user.js
Labels: Fix, Add

#32 [ADD] Setup for using `openai`
  libs/openai.js
  package-lock.json
  package.json
Labels: Add

#34 [FIX] Setup for using `openai`, etc.
  .github/workflows/github-actions.yaml
  app.js
  controllers/user.js
  routes/gpt.js
  routes/index.js
  routes/kogpt.js
  routes/user.js
  tests/app.test.js
Labels: Fix, Add, Chore

#35 [FIX] 프롬프트 구체화
  routes/gpt.js
Labels: Fix

#36 [FIX] Cookies `maxAge` unit issue, etc.
  app.js
  routes/gpt.js
  routes/user.js
Labels: Fix

#37 [FIX] Feature `/gpt/*` routes, etc.
  middlewares/afterUsingGPT.js
  middlewares/isAffordablePoint.js
  routes/gpt.js
  routes/user.js
  tests/app.test.js
Labels: Fix, Add, Chore

#38 [ADD] PreDeployment works
  app.js
  config/config.js
  logger.js
  middlewares/errorHandler.js
  models/index.js
  package-lock.json
  package.json
  server.js
  tests/app.test.js
Labels: Add

#39 [FIX] modified setting for deploy
  app.js
  config/config.js
Labels: Fix

#40 [ADD] `ecosystem.config.js` for pm2
  .gitignore
  ecosystem.config.js
Labels: Add

#41 [FIX] CORS setting
  app.js
  ecosystem.config.js
Labels: Fix

#43 [ADD] Readme.md
  README.md
Labels: Add

#44 Update README.md
  README.md
Labels: Chore
